version: "3"
services:
  db:
    image: postgres:12
    volumes:
      - pg-vol:/var/lib/postgresql/data/
      - ./backend/dbbackup:/dbbackup/
    env_file:
      - ./backend/pg_settings.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app/backend
      - static-vol:/app/backend/staticfiles/
    stdin_open: true
    tty: true
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    #ports:
    #  - 8000:8000
    expose:
      - 8000
    environment:
      MYSQL_HOST: host.docker.internal
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static-vol:/app/backend/staticfiles/
      - ./data/certbot/conf:/etc/letsencrypt/
      - ./data/certbot/www:/var/www/certbot/
    ports:
      - 1337:80
      - 443:443
    depends_on:
      - backend
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt/
      - ./data/certbot/www:/var/www/certbot/
volumes:
  pg-vol:
  static-vol:
